apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-dev'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/EngKe/ArgoCD.git
        targetRevision: main
        path: argoapps
      destination:
        server: '{{url}}'
        namespace: dev
      syncPolicy:
         syncOptions:
          - CreateNamespace=true
