apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: nginx-app
  namespace: argocd
spec: 
  destination: 
    namespace: dev
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argocd/nginx
    repoURL: "https://github.com/EngKe/ArgoCD.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
