name: Repository Dispatch

on:
  repository_dispatch:
    types: [new-image]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: clone repo
      uses: EngKe/ArgoCD/.github/actions/repo-clone@dev
      with:
        repo: github.com/EngKe/ArgoCD.git
        key: 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
        branch: dev
        
    - name: Update Image Version
      uses: EngKe/ArgoCD/.github/actions/update-image@dev
      with:
        image: ${{ github.event.client_payload.image }}
        file: pythonapp/deployment.yaml
    - name: open pr
      run: |
        cd ArgoCD
        git add .
        git commit -m "Apply image name changes"
        git status
        git push
        gh pr create --base main --head dev --title "The bug is fixed" --body "Everything works again"
      env:
        GH_TOKEN: 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
