name: Repository Dispatch

on:
  repository_dispatch:
    types: [new-image]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update Image Version
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        ref: dev

    - name: Update Image Version
      id: imgupd
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i pythonapp/deployment.yaml 
    
    - name: open pr
      run: |
        echo "${{ secrets.EMAIL }}"
        echo "${{ secrets.USERNAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "${{ secrets.USERNAME }}"
        git add .
        git commit -m "Apply image name changes"
        git status
        git push origin dev
        git request-pull dev origin main

