name: Repository Dispatch

on:
  workflow_dispatch:
  repository_dispatch:
    types: [new-image]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: clone repo
      uses: ./.github/actions/repo-clone/action.yml
      with:
        repo: github.com/EngKe/ArgoCD.git
        key: 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
        branch: dev
        
    - name: Update Image Version
      id: imgupd
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i ArgoCD/pythonapp/deployment.yaml 
    
    - name: open pr
      run: |
        cd ArgoCD
        git config --global user.email "kesginengin@gmail.com"
        git config --global user.name "EngKe"
        git add .
        git commit -m "Apply image name changes"
        git status
        git push
        gh pr create --base main --head dev --title "The bug is fixed" --body "Everything works again"
      env:
        GH_TOKEN: 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
